### ISSUE TITLE
Erreur sur la page d'installation du plugin Gsuite

### ISSUE THREAD

**Issue by Deghinsea** [centreon/centreon-documentation#666]
**Describe the bug**
Sur la page d'installation du plugin Gsuite (https://docs.centreon.com/20.04/fr/integrations/plugin-packs/procedures/applications-google-gsuite-api.html) il y a une erreur dans la commande d'installation du plugin.

**Expected behavior**
Il faut modifier la commande décrite dans la partie "Installation", point 1 et l'autre point 1 un peu plus loin : 
_yum install centreon-plugin-centreon-plugin-Applications-Google-Gsuite-Api_
pour
_yum install centreon-plugin-Applications-Google-Gsuite-Api_

**Comment by Sims24** [comment]
Fixed here https://github.com/centreon/centreon-documentation/pull/561 and there https://github.com/centreon/centreon-documentation/pull/560

**Comment by Sims24** [comment]
Thanks @Deghinsea for your report. 

It's now fixed and online! 

Cheers

**Comment by Deghinsea** [comment]
Hello,

I saw the fix for the first order. But the same error remains for the second command (see the attached capture).

Regards,

Deghinsea

![image](https://user-images.githubusercontent.com/82508562/115196901-b8536380-a0f0-11eb-8315-3c29a49fd25e.png)
